### ISSUE TITLE
[SUG] Create Groups for YTCR

### ISSUE THREAD

**Issue by KiokuVT** [gezelio/YTCR#55]
Within the YTCR Page, Create groups or "Folders" Streamers can create that they can use in order to Organize their actions. For example the Viewer clicks the CR Button, Folders pop up named "Sounds" "Games" "Videos" and then the viewer clicks the folder and it shows the actions to redeem.

**Comment by trent-gezel** [comment]
![Image](https://github.com/gezelio/YTCR/assets/64388078/b15602e6-0332-4f74-8fce-b474b2dfb303)


![Image](https://github.com/gezelio/YTCR/assets/64388078/c85ea9a1-dec5-433e-a954-e205a5cec1b3)

**Comment by trent-gezel** [comment]
Adding colours to buttons created on the site

![Image](https://github.com/gezelio/YTCR/assets/64388078/46e362ba-de90-49be-85f1-b90cad825656)

**Comment by tommerty** [comment]
Closing as pushed to `staging` and will be merged with v2.0.1
