### ISSUE TITLE
[SUG] Redeem Cooldowns

### ISSUE THREAD

**Issue by KiokuVT** [gezelio/YTCR#62]
For the online site it would be awesome to incorporate a cooldown mechanic. As it stand users can spam redeems with bo CD available. I recommending having a setting within the site that states "Global Cooldown" "User Cooldown" "Uses per stream" and lastly "Uses per User"
"Global Cooldown" is for all user to wait to use that redeem.
"User Cooldown" is for redeems specifically for that user who used it. So the redeem can be used immediately by other but have to wait from the same user 
"Uses per stream" like a "first" redeem should only be able to be used once a stream.
"Uses per user" same as user cooldown but only limited to that many for that user 

The important part is that once the cooldown is activate that the redeem button does not allow you to click it and a message does NOT send "user redeemed Action"

Much Love.

**Comment by tommerty** [comment]
work has started https://github.com/gezelio/YTCR/commit/c5f7ecf1c946103d805b96ebe8847f7e0ab8c53f
